In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('StudentsPerformance.csv')

In [4]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
df.shape

(1000, 8)

In [6]:
df.size

8000

In [7]:
df.head(1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74

In [8]:
df.tail(1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
999,female,group D,some college,free/reduced,none,77,86,86

In [9]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [10]:
df[["lunch"]]

            lunch
0        standard
1        standard
2        standard
3    free/reduced
4        standard
..            ...
995      standard
996  free/reduced
997  free/reduced
998      standard
999  free/reduced

[1000 rows x 1 columns]

In [11]:
df.loc[df.gender=='female']

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [12]:
df[(df['math score']>70)]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
984,female,group C,some high school,standard,none,74,75,82
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
995,female,group E,master's degree,standard,completed,88,99,95
999,female,group D,some college,free/reduced,none,77,86,86

In [13]:
df.query("`math score`>70 and gender== 'male' and `reading score`<50")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
520,male,group D,some college,standard,none,71,49,52

In [14]:
df.loc[520,'reading score']=50

In [15]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [16]:
df.loc[[520]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
520,male,group D,some college,standard,none,71,50,52

In [17]:
df['reading score'].sum()

np.int64(69170)

In [18]:
df['math score'].max()

np.int64(100)

In [19]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [20]:
df.fillna(0)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [21]:
df.query("`math score`==0")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10

In [22]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [37]:
df.iloc[[58]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df.isnull().sum()

gender                         1
race/ethnicity                 1
parental level of education    1
lunch                          1
test preparation course        1
math score                     1
reading score                  1
writing score                  1
dtype: int64

In [47]:
df.iloc[[4]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
4,male,group C,some college,standard,none,76.0,78.0,75.0

In [51]:
df.loc[4,'math score']=80

In [52]:
df.iloc[[4]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
4,male,group C,some college,standard,none,80.0,78.0,75.0

In [55]:
df.loc[4,'math score']=np.nan

In [56]:
df.iloc[[4]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
4,male,group C,some college,standard,none,NaN,78.0,75.0

In [60]:
df.fillna(50)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0
1,female,group C,some college,standard,completed,69.0,90.0,88.0
2,female,group B,master's degree,standard,none,90.0,95.0,93.0
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0
4,male,group C,some college,standard,none,50.0,78.0,75.0
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99.0,95.0
996,male,group C,high school,free/reduced,none,62.0,55.0,55.0
997,female,group C,high school,free/reduced,completed,59.0,71.0,65.0
998,female,group D,some college,standard,completed,68.0,78.0,77.0
999,female,group D,some college,free/reduced,none,77.0,86.0,86.0

In [66]:
df.loc[58,'math score']=90

In [67]:
df.iloc[[58]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
58,NaN,NaN,NaN,NaN,NaN,90.0,NaN,NaN

In [70]:
df['total']=np.nan

In [71]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,NaN
1,female,group C,some college,standard,completed,69.0,90.0,88.0,NaN
2,female,group B,master's degree,standard,none,90.0,95.0,93.0,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,NaN
4,male,group C,some college,standard,none,NaN,78.0,75.0,NaN
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99.0,95.0,NaN
996,male,group C,high school,free/reduced,none,62.0,55.0,55.0,NaN
997,female,group C,high school,free/reduced,completed,59.0,71.0,65.0,NaN
998,female,group D,some college,standard,completed,68.0,78.0,77.0,NaN
999,female,group D,some college,free/reduced,none,77.0,86.0,86.0,NaN

In [72]:
df.fillna('missing')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,missing
1,female,group C,some college,standard,completed,69.0,90.0,88.0,missing
2,female,group B,master's degree,standard,none,90.0,95.0,93.0,missing
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,missing
4,male,group C,some college,standard,none,missing,78.0,75.0,missing
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99.0,95.0,missing
996,male,group C,high school,free/reduced,none,62.0,55.0,55.0,missing
997,female,group C,high school,free/reduced,completed,59.0,71.0,65.0,missing
998,female,group D,some college,standard,completed,68.0,78.0,77.0,missing
999,female,group D,some college,free/reduced,none,77.0,86.0,86.0,missing

In [73]:
df.loc[999,'total']=100

In [74]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,NaN
1,female,group C,some college,standard,completed,69.0,90.0,88.0,NaN
2,female,group B,master's degree,standard,none,90.0,95.0,93.0,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,NaN
4,male,group C,some college,standard,none,NaN,78.0,75.0,NaN
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99.0,95.0,NaN
996,male,group C,high school,free/reduced,none,62.0,55.0,55.0,NaN
997,female,group C,high school,free/reduced,completed,59.0,71.0,65.0,NaN
998,female,group D,some college,standard,completed,68.0,78.0,77.0,NaN
999,female,group D,some college,free/reduced,none,77.0,86.0,86.0,100.0

In [75]:
df.query("total==100")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
999,female,group D,some college,free/reduced,none,77.0,86.0,86.0,100.0

In [78]:
df.groupby('gender')['reading score'].sum()

gender
female    37611.0
male      31500.0
Name: reading score, dtype: float64

In [79]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,NaN
1,female,group C,some college,standard,completed,69.0,90.0,88.0,NaN
2,female,group B,master's degree,standard,none,90.0,95.0,93.0,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,NaN
4,male,group C,some college,standard,none,NaN,78.0,75.0,NaN
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99.0,95.0,NaN
996,male,group C,high school,free/reduced,none,62.0,55.0,55.0,NaN
997,female,group C,high school,free/reduced,completed,59.0,71.0,65.0,NaN
998,female,group D,some college,standard,completed,68.0,78.0,77.0,NaN
999,female,group D,some college,free/reduced,none,77.0,86.0,86.0,100.0

In [80]:
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,NaN
1,female,group C,some college,standard,completed,69.0,90.0,88.0,NaN
2,female,group B,master's degree,standard,none,90.0,95.0,93.0,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0,NaN
4,male,group C,some college,standard,none,NaN,78.0,75.0,NaN
5,female,group B,associate's degree,standard,none,71.0,83.0,78.0,NaN
6,female,group B,some college,standard,completed,88.0,95.0,92.0,NaN
7,male,group B,some college,free/reduced,none,40.0,43.0,39.0,NaN
8,male,group D,high school,free/reduced,completed,64.0,64.0,67.0,NaN
9,female,group B,high school,free/reduced,none,38.0,60.0,50.0,NaN

In [81]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
995,female,group E,master's degree,standard,completed,88.0,99.0,95.0,NaN
996,male,group C,high school,free/reduced,none,62.0,55.0,55.0,NaN
997,female,group C,high school,free/reduced,completed,59.0,71.0,65.0,NaN
998,female,group D,some college,standard,completed,68.0,78.0,77.0,NaN
999,female,group D,some college,free/reduced,none,77.0,86.0,86.0,100.0

In [82]:
df.shape

(1000, 9)

In [85]:
df.loc[[0]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72.0,74.0,NaN

In [89]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'total'],
      dtype='str')

In [91]:
type(df)

pandas.DataFrame

In [94]:
df.dtypes

gender                             str
race/ethnicity                     str
parental level of education        str
lunch                              str
test preparation course            str
math score                     float64
reading score                  float64
writing score                  float64
total                          float64
dtype: object