In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('StudentsPerformance.csv')

In [4]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# LEVEL 1 — Basic Pandas Practice (1–15)

**First 10 rows print karo.**

In [5]:
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

**Last 5 rows print karo.**

In [6]:
df.tail(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

**Dataset ka shape nikalo.**

In [7]:
df.shape

(1000, 8)

**Column names print karo.**

In [8]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

**Data types check karo.**

In [9]:
df.dtypes

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

**Numeric columns identify karo.**

In [10]:
df.dtypes

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

**Kisi bhi ek column ki unique values nikalo.**

In [11]:
df['math score'].unique()

array([ 72,  69,  90,  47,  76,  71,  88,  40,  64,  38,  58,  65,  78,
        50,  18,  46,  54,  66,  44,  74,  73,  67,  70,  62,  63,  56,
        97,  81,  75,  57,  55,  53,  59,  82,  77,  33,  52,   0,  79,
        39,  45,  60,  61,  41,  49,  30,  80,  42,  27,  43,  68,  85,
        98,  87,  51,  99,  84,  91,  83,  89,  22, 100,  96,  94,  48,
        35,  34,  86,  92,  37,  28,  24,  26,  95,  36,  29,  32,  93,
        19,  23,   8])

**Total null values count karo.**

In [12]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

**Check karo duplicate rows hain ya nah**

In [13]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

**Sirf math score column print karo**

In [14]:
df['math score']

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

**math score > 80 wale students filter karo.**

In [15]:
df.query("`math score`>80")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90,95,93
6,female,group B,some college,standard,completed,88,95,92
16,male,group C,high school,standard,none,88,89,86
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
...,...,...,...,...,...,...,...,...
979,female,group C,associate's degree,standard,none,91,95,94
981,male,group D,some high school,standard,none,81,78,78
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
995,female,group E,master's degree,standard,completed,88,99,95

**gender == female rows print karo.**

In [16]:
df[df.gender=='female']

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

**standard lunch wale students count karo.**

In [17]:
df.query("lunch=='standard'").count()

gender                         645
race/ethnicity                 645
parental level of education    645
lunch                          645
test preparation course        645
math score                     645
reading score                  645
writing score                  645
dtype: int64

**completed test preparation wale students count karo.**

In [18]:
df.query("`test preparation course`=='completed'").count()

gender                         358
race/ethnicity                 358
parental level of education    358
lunch                          358
test preparation course        358
math score                     358
reading score                  358
writing score                  358
dtype: int64

# LEVEL 2 — Filtering + Logic Building (16–30)

**1.Math me 90+ score wale students nikalo.**

In [19]:
df.query("`math score`>90 and gender=='male'")[['gender', 'math score']]#if print only two specific column

    gender  math score
34    male          97
104   male          98
121   male          91
149   male         100
171   male          94
233   male          92
286   male          97
306   male          99
469   male          91
539   male          97
562   male          96
571   male          91
612   male          94
618   male          95
623   male         100
625   male         100
689   male          93
710   male          93
719   male          91
736   male          92
779   male          94
784   male          91
815   male          94
846   male          91
864   male          97
916   male         100
919   male          91
934   male          98
950   male          94

**Reading me fail (<40) students nikalo.**

In [20]:
df.query("`reading score`<40")[['gender','reading score']]

     gender  reading score
17   female             32
59   female             17
61     male             39
66     male             37
76     male             26
84     male             39
91     male             34
131    male             37
145  female             39
211    male             28
327    male             23
331    male             37
338  female             38
363  female             34
424    male             39
466  female             31
555  female             39
596    male             24
601  female             29
706    male             34
729    male             39
787  female             38
810    male             31
895  female             34
896    male             29
980  female             24

**Math + reading dono me 80+ wale students nikalo.**

In [21]:
df.query("`math score`>80 and `reading score`>80")[['gender','math score','reading score']]

     gender  math score  reading score
2    female          90             95
6    female          88             95
16     male          88             89
34     male          97             87
35     male          81             81
..      ...         ...            ...
962  female         100            100
970  female          89            100
979  female          91             95
990    male          86             81
995  female          88             99

[131 rows x 3 columns]

**Female students ka average writing score nikalo**

In [22]:
df.query("gender=='female'")[['writing score']].mean()

writing score    72.467181
dtype: float64

**Male students ka average math score nikalo.**

In [23]:
df.query("gender=='male'")[['writing score']].mean()

writing score    63.311203
dtype: float64

**free/reduced lunch students ka average score nikalo.**

In [24]:
df.query("lunch=='free/reduced'")[['math score','reading score','writing score']].mean()

math score       58.921127
reading score    64.653521
writing score    63.022535
dtype: float64

**Test prep completed vs none ka average compare karo**

In [25]:
comp=pd.DataFrame({
    'complete':df.query("`test preparation course`=='completed'")[['math score','reading score','writing score']].mean(),
    'none':df.query("`test preparation course`=='none'")[['math score','reading score','writing score']].mean()
})

In [26]:
comp

                complete       none
math score     69.695531  64.077882
reading score  73.893855  66.534268
writing score  74.418994  64.504673

**Kaunsi gender ka reading score highest hai?**

In [27]:
df.groupby("gender")[['reading score']].max()

        reading score
gender
female            100
male              100

**Har race group ka average math score nikalo.**

In [28]:
df.groupby('race/ethnicity')['math score'].mean()

race/ethnicity
group A    61.629213
group B    63.452632
group C    64.463950
group D    67.362595
group E    73.821429
Name: math score, dtype: float64

In [29]:
df.groupby('race/ethnicity')['math score'].mean().idxmin()

'group A'

**Parent education ke basis pe average scores compare karo.**

In [30]:
df.groupby("parental level of education")[['math score','reading score','writing score']].mean(),


df.groupby("parental level of education")[['math score','reading score','writing score']].mean()

                             math score  reading score  writing score
parental level of education
associate's degree            67.882883      70.927928      69.896396
bachelor's degree             69.389831      73.000000      73.381356
high school                   62.137755      64.704082      62.448980
master's degree               69.745763      75.372881      75.677966
some college                  67.128319      69.460177      68.840708
some high school              63.497207      66.938547      64.888268

**Top 10 highest math score students nikalo.**

In [31]:
df.sort_values('math score',ascending=False)[['gender','math score']].head(10)

     gender  math score
451  female         100
458  female         100
962  female         100
149    male         100
623    male         100
625    male         100
916    male         100
114  female          99
263  female          99
306    male          99

**Lowest writing score students nikalo.**

In [32]:
df.sort_values('writing score')[['gender','writing score']].head(10)

     gender  writing score
59   female             10
596    male             15
327    male             19
76     male             22
980  female             23
211    male             27
338  female             27
896    male             27
17   female             28
601  female             30

**Students ko math score descending order me sort karo.**

In [33]:
df.sort_values('math score',ascending=False)[['gender','math score']]

     gender  math score
451  female         100
458  female         100
962  female         100
149    male         100
623    male         100
..      ...         ...
145  female          22
787  female          19
17   female          18
980  female           8
59   female           0

[1000 rows x 2 columns]

**Sirf selected columns ka new DataFrame banao.**

In [34]:
df1=pd.DataFrame({
    'gen_name': df.query("gender=='male'")['gender']
})

In [35]:
df1

    gen_name
3       male
4       male
7       male
8       male
10      male
..       ...
985     male
987     male
990     male
994     male
996     male

[482 rows x 1 columns]

**Ek new column total score banao.**

In [36]:
df['Total score'] = df[['math score', 'reading score', 'writing score']].sum(axis=1)

In [37]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

In [38]:
df.fillna("missing")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

# LEVEL 3 — Real Analysis Questions (31–40)

**average score naam ka column banao.**

In [39]:
df['avg score']=df[['math score', 'reading score', 'writing score']].mean(axis=1)

In [40]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total score,avg score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282,94.000000
996,male,group C,high school,free/reduced,none,62,55,55,172,57.333333
997,female,group C,high school,free/reduced,completed,59,71,65,195,65.000000
998,female,group D,some college,standard,completed,68,78,77,223,74.333333
999,female,group D,some college,free/reduced,none,77,86,86,249,83.000000

**Highest average score wala student find karo.**

In [41]:
df.sort_values('avg score')[['gender','avg score']].max()

gender        male
avg score    100.0
dtype: object

**Lowest average score wala student find karo.**

In [42]:
df.sort_values('avg score')[['gender','avg score']].min()

gender       female
avg score       9.0
dtype: object

**Pass/fail column banao:
average >= 40 → Pass
otherwise Fail**

In [43]:
df['pass/fail']=np.where(df['math score'] >=40,'pass','fail')

In [44]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total score,avg score,pass/fail
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667,pass
1,female,group C,some college,standard,completed,69,90,88,247,82.333333,pass
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667,pass
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333,pass
4,male,group C,some college,standard,none,76,78,75,229,76.333333,pass
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282,94.000000,pass
996,male,group C,high school,free/reduced,none,62,55,55,172,57.333333,pass
997,female,group C,high school,free/reduced,completed,59,71,65,195,65.000000,pass
998,female,group D,some college,standard,completed,68,78,77,223,74.333333,pass
999,female,group D,some college,free/reduced,none,77,86,86,249,83.000000,pass

**Total pass students count karo.**

In [45]:
df.query("`pass/fail`=='pass'")[['pass/fail']].count()

pass/fail    960
dtype: int64

**Total fail students count karo.**

In [46]:
df.query("`pass/fail`=='fail'")[['pass/fail']].count()

pass/fail    40
dtype: int64

**Kaunsi subject me highest average hai?**

In [47]:
df.query("`math score` and `reading score` and `writing score`")[['math score','reading score','writing score']].mean().idxmax()

'reading score'

**Math vs reading correlation nikalo.**

In [48]:
df[['math score','reading score']].corr()

               math score  reading score
math score        1.00000        0.81758
reading score     0.81758        1.00000

# LEVEL 4 — NumPy + Advanced Pandas Logic (41–50)

**NumPy use karke total score array banao.**

In [54]:
ts=np.array(df['Total score'])

In [55]:
ts

array([218, 247, 278, 148, 229, 232, 275, 122, 195, 148, 164, 135, 219,
       220, 161, 222, 263,  78, 134, 173, 198, 210, 151, 215, 225, 219,
       178, 211, 205, 207, 217, 189, 193, 120, 266, 241, 238, 173, 253,
       170, 170, 199, 176, 190, 160, 176, 182, 213, 207, 248, 156, 214,
       139, 241, 242, 117, 253, 156, 175,  27, 225, 112, 178, 220, 176,
       192, 119, 206, 175, 160, 194, 181, 140, 174, 139, 123,  78, 239,
       207, 198, 146, 139, 151, 199, 115, 235, 247, 216, 195, 241, 211,
        97, 221, 138, 257, 241, 193, 205, 187, 194, 213, 216, 265, 151,
       274, 197, 287, 193, 198, 206, 264, 166, 154, 163, 299, 235, 242,
       239, 175, 189, 260, 272, 274, 176, 236, 268, 207, 216, 238, 151,
       255, 130, 231, 240, 228, 161, 146, 181, 192, 201, 219, 185, 151,
       147, 239,  94, 247, 207, 224, 293, 198, 212, 195, 150, 190, 247,
       218, 180, 234, 192, 234, 248, 154, 154, 264, 296, 155, 212, 229,
       212, 219, 260, 246, 200, 148, 259, 158, 225, 184, 297, 205, 176,
       147, 204, 146, 197, 221, 196, 145, 252, 200, 238, 192, 201, 238,
       168, 193, 162, 153, 233, 237, 223, 215, 194, 142, 223, 206, 237,
       231, 185, 238,  90, 164, 167, 259, 242, 257, 115, 213, 173, 198,
       245, 182, 241, 191, 155, 215, 161, 204, 277, 206, 131, 236, 257,
       249, 232, 196, 198, 157, 244, 207, 246, 163, 153, 218, 232, 239,
       196, 191, 181, 145, 237, 200, 232, 158, 205, 205, 232, 223, 227,
       220, 236, 145, 282, 217, 142, 219, 218, 275, 217, 193, 149, 158,
       206, 249, 234, 270, 197, 231, 186, 147, 139, 236, 226, 129, 245,
       267, 238, 239, 230, 214, 229, 180, 213, 235, 189, 130, 213, 136,
       252, 240, 162, 232, 220, 232, 205, 267, 147, 191, 158, 229, 183,
       196, 204, 198, 202, 250, 233, 203, 184, 230, 240, 232, 149, 130,
       266, 184,  70, 234, 147, 192, 119, 171, 249, 271, 195, 215, 143,
        89, 150, 171, 197, 219, 206, 219, 227, 180, 266, 215, 237, 186,
       175, 221, 161, 200, 203, 185, 177, 182, 259, 179, 247, 168,  93,
       177, 167, 180, 188, 166, 242, 232, 188, 220, 275, 202, 130, 252,
       280, 231, 192, 249, 282, 231, 132, 124, 218, 207, 202, 190, 218,
       199, 222, 210, 167, 216, 134, 180, 269, 194, 173, 180, 139, 169,
       287, 175, 204, 193, 239, 165, 256, 215, 245, 197, 197, 202, 226,
       213, 214, 189, 167, 268, 179, 172, 224, 114, 191, 255, 205, 177,
       185, 189, 203, 172, 156, 205, 151, 207, 214, 177, 259, 227, 239,
       201, 232, 234, 218, 195, 247, 135, 226, 234, 289, 216, 172, 176,
       140, 257, 155, 300, 205, 166, 153, 217, 258, 195, 262,  95, 204,
       250, 241, 258, 206, 238, 187, 271, 230, 204, 220, 189, 214, 212,
       167, 197, 157, 155, 215, 164, 209, 174, 243, 226, 198, 256, 259,
       186, 198, 154, 213, 203, 219, 235, 273, 178, 276, 153, 244, 204,
       168, 234, 265, 220, 157, 163, 177, 268, 248, 247, 213, 222, 224,
       172, 261, 184, 163, 154, 187, 177, 132, 117, 206, 208, 154, 181,
       261, 210, 232, 169, 179, 222, 275, 212, 241, 237, 266, 193, 241,
       289, 203, 193, 220, 220, 265, 138, 203, 138, 104, 206, 194, 193,
       201, 228, 211, 278, 223, 145, 136, 292, 210, 158, 203, 216, 279,
       171, 180, 226, 148, 164, 261, 162, 182, 274, 236, 214, 228, 223,
       217, 201, 169, 183, 179, 169, 183, 200, 223, 291, 207,  69, 155,
       219, 228, 177,  88, 234, 168, 263, 209, 251, 152, 187, 186, 192,
       183, 275, 216, 268, 200, 120, 249, 260, 206, 150, 181, 161, 282,
       181, 296, 202, 155, 152, 150, 201, 204, 221, 248, 248, 209, 228,
       260, 236, 223, 144, 252, 232, 233, 195, 227, 194, 194, 158, 229,
       160, 224, 269, 209, 231, 196, 208, 196, 161, 262, 224, 202, 195,
       201, 206, 170, 207, 249, 208, 230, 210, 159, 223, 233, 224, 180,
       227, 228, 234, 184, 213, 188, 171, 113, 196, 293, 228, 228, 155,
       266, 155, 227, 221, 227, 168, 254, 247, 201, 214, 191, 242, 196,
       258, 194, 186, 199, 116, 177, 255, 161, 267, 250, 297, 246, 204,
       257, 223, 291, 226, 244, 204, 173, 252, 140, 131, 226, 217, 176,
       249, 129, 225, 144, 270, 146, 168, 183, 255, 192, 225, 176, 225,
       150, 247, 204, 157, 225, 215, 201, 169, 257, 208, 205, 231, 252,
       166, 271, 165, 210, 176, 223, 189, 160, 245, 187, 182, 218, 210,
       198, 214, 175, 149, 222, 191, 219, 191, 162, 208, 122, 233, 261,
       159, 251, 243, 173, 251, 127, 228,  89, 194, 178, 170, 196, 209,
       250, 145, 198, 210, 235, 183, 164, 208, 229, 276, 254, 227, 230,
       213, 126, 234, 164, 118, 141, 185, 247, 235, 267, 168, 207, 200,
       256, 267, 261, 152, 240, 158, 187, 194, 210, 236, 175, 178, 249,
       182, 248, 153, 198, 194, 236, 168, 216, 137, 173, 103, 227, 169,
       259, 261, 168, 199, 224, 205, 192, 265, 210, 181, 290, 208, 225,
       147, 232, 168, 254, 119, 222, 281, 252, 164, 144, 224, 151, 164,
       218, 244, 262, 166, 210, 247, 172, 211, 214, 193, 211, 208, 145,
       156, 218, 288, 185, 208, 143, 262, 262, 190, 237, 190, 104,  92,
       220, 184, 225, 258, 225, 123, 293, 235, 242, 156, 254, 214, 204,
       140, 235, 179, 175, 162, 204, 300, 157, 214, 278, 206, 134, 204,
       184, 213, 198, 172, 197, 133, 155, 211, 181, 205, 219, 275, 191,
       177, 172, 251, 214, 210, 265, 211, 184, 187, 173, 244, 167, 151,
       205, 238, 235, 220, 164, 200, 191, 252, 292, 167, 227, 178, 155,
       300, 216, 187, 204, 198, 186, 211, 239, 289, 219, 163, 175, 184,
       223, 182, 185, 144, 280,  55, 237, 250, 256, 231, 162, 150, 232,
       134, 236, 242, 225, 207, 208, 188, 282, 172, 195, 223, 249])

In [64]:
ts.size

1000

**NumPy boolean indexing se 90+ students nikalo.**

In [80]:
ts[ts>90]

array([218, 247, 278, 148, 229, 232, 275, 122, 195, 148, 164, 135, 219,
       220, 161, 222, 263, 134, 173, 198, 210, 151, 215, 225, 219, 178,
       211, 205, 207, 217, 189, 193, 120, 266, 241, 238, 173, 253, 170,
       170, 199, 176, 190, 160, 176, 182, 213, 207, 248, 156, 214, 139,
       241, 242, 117, 253, 156, 175, 225, 112, 178, 220, 176, 192, 119,
       206, 175, 160, 194, 181, 140, 174, 139, 123, 239, 207, 198, 146,
       139, 151, 199, 115, 235, 247, 216, 195, 241, 211,  97, 221, 138,
       257, 241, 193, 205, 187, 194, 213, 216, 265, 151, 274, 197, 287,
       193, 198, 206, 264, 166, 154, 163, 299, 235, 242, 239, 175, 189,
       260, 272, 274, 176, 236, 268, 207, 216, 238, 151, 255, 130, 231,
       240, 228, 161, 146, 181, 192, 201, 219, 185, 151, 147, 239,  94,
       247, 207, 224, 293, 198, 212, 195, 150, 190, 247, 218, 180, 234,
       192, 234, 248, 154, 154, 264, 296, 155, 212, 229, 212, 219, 260,
       246, 200, 148, 259, 158, 225, 184, 297, 205, 176, 147, 204, 146,
       197, 221, 196, 145, 252, 200, 238, 192, 201, 238, 168, 193, 162,
       153, 233, 237, 223, 215, 194, 142, 223, 206, 237, 231, 185, 238,
       164, 167, 259, 242, 257, 115, 213, 173, 198, 245, 182, 241, 191,
       155, 215, 161, 204, 277, 206, 131, 236, 257, 249, 232, 196, 198,
       157, 244, 207, 246, 163, 153, 218, 232, 239, 196, 191, 181, 145,
       237, 200, 232, 158, 205, 205, 232, 223, 227, 220, 236, 145, 282,
       217, 142, 219, 218, 275, 217, 193, 149, 158, 206, 249, 234, 270,
       197, 231, 186, 147, 139, 236, 226, 129, 245, 267, 238, 239, 230,
       214, 229, 180, 213, 235, 189, 130, 213, 136, 252, 240, 162, 232,
       220, 232, 205, 267, 147, 191, 158, 229, 183, 196, 204, 198, 202,
       250, 233, 203, 184, 230, 240, 232, 149, 130, 266, 184, 234, 147,
       192, 119, 171, 249, 271, 195, 215, 143, 150, 171, 197, 219, 206,
       219, 227, 180, 266, 215, 237, 186, 175, 221, 161, 200, 203, 185,
       177, 182, 259, 179, 247, 168,  93, 177, 167, 180, 188, 166, 242,
       232, 188, 220, 275, 202, 130, 252, 280, 231, 192, 249, 282, 231,
       132, 124, 218, 207, 202, 190, 218, 199, 222, 210, 167, 216, 134,
       180, 269, 194, 173, 180, 139, 169, 287, 175, 204, 193, 239, 165,
       256, 215, 245, 197, 197, 202, 226, 213, 214, 189, 167, 268, 179,
       172, 224, 114, 191, 255, 205, 177, 185, 189, 203, 172, 156, 205,
       151, 207, 214, 177, 259, 227, 239, 201, 232, 234, 218, 195, 247,
       135, 226, 234, 289, 216, 172, 176, 140, 257, 155, 300, 205, 166,
       153, 217, 258, 195, 262,  95, 204, 250, 241, 258, 206, 238, 187,
       271, 230, 204, 220, 189, 214, 212, 167, 197, 157, 155, 215, 164,
       209, 174, 243, 226, 198, 256, 259, 186, 198, 154, 213, 203, 219,
       235, 273, 178, 276, 153, 244, 204, 168, 234, 265, 220, 157, 163,
       177, 268, 248, 247, 213, 222, 224, 172, 261, 184, 163, 154, 187,
       177, 132, 117, 206, 208, 154, 181, 261, 210, 232, 169, 179, 222,
       275, 212, 241, 237, 266, 193, 241, 289, 203, 193, 220, 220, 265,
       138, 203, 138, 104, 206, 194, 193, 201, 228, 211, 278, 223, 145,
       136, 292, 210, 158, 203, 216, 279, 171, 180, 226, 148, 164, 261,
       162, 182, 274, 236, 214, 228, 223, 217, 201, 169, 183, 179, 169,
       183, 200, 223, 291, 207, 155, 219, 228, 177, 234, 168, 263, 209,
       251, 152, 187, 186, 192, 183, 275, 216, 268, 200, 120, 249, 260,
       206, 150, 181, 161, 282, 181, 296, 202, 155, 152, 150, 201, 204,
       221, 248, 248, 209, 228, 260, 236, 223, 144, 252, 232, 233, 195,
       227, 194, 194, 158, 229, 160, 224, 269, 209, 231, 196, 208, 196,
       161, 262, 224, 202, 195, 201, 206, 170, 207, 249, 208, 230, 210,
       159, 223, 233, 224, 180, 227, 228, 234, 184, 213, 188, 171, 113,
       196, 293, 228, 228, 155, 266, 155, 227, 221, 227, 168, 254, 247,
       201, 214, 191, 242, 196, 258, 194, 186, 199, 116, 177, 255, 161,
       267, 250, 297, 246, 204, 257, 223, 291, 226, 244, 204, 173, 252,
       140, 131, 226, 217, 176, 249, 129, 225, 144, 270, 146, 168, 183,
       255, 192, 225, 176, 225, 150, 247, 204, 157, 225, 215, 201, 169,
       257, 208, 205, 231, 252, 166, 271, 165, 210, 176, 223, 189, 160,
       245, 187, 182, 218, 210, 198, 214, 175, 149, 222, 191, 219, 191,
       162, 208, 122, 233, 261, 159, 251, 243, 173, 251, 127, 228, 194,
       178, 170, 196, 209, 250, 145, 198, 210, 235, 183, 164, 208, 229,
       276, 254, 227, 230, 213, 126, 234, 164, 118, 141, 185, 247, 235,
       267, 168, 207, 200, 256, 267, 261, 152, 240, 158, 187, 194, 210,
       236, 175, 178, 249, 182, 248, 153, 198, 194, 236, 168, 216, 137,
       173, 103, 227, 169, 259, 261, 168, 199, 224, 205, 192, 265, 210,
       181, 290, 208, 225, 147, 232, 168, 254, 119, 222, 281, 252, 164,
       144, 224, 151, 164, 218, 244, 262, 166, 210, 247, 172, 211, 214,
       193, 211, 208, 145, 156, 218, 288, 185, 208, 143, 262, 262, 190,
       237, 190, 104,  92, 220, 184, 225, 258, 225, 123, 293, 235, 242,
       156, 254, 214, 204, 140, 235, 179, 175, 162, 204, 300, 157, 214,
       278, 206, 134, 204, 184, 213, 198, 172, 197, 133, 155, 211, 181,
       205, 219, 275, 191, 177, 172, 251, 214, 210, 265, 211, 184, 187,
       173, 244, 167, 151, 205, 238, 235, 220, 164, 200, 191, 252, 292,
       167, 227, 178, 155, 300, 216, 187, 204, 198, 186, 211, 239, 289,
       219, 163, 175, 184, 223, 182, 185, 144, 280, 237, 250, 256, 231,
       162, 150, 232, 134, 236, 242, 225, 207, 208, 188, 282, 172, 195,
       223, 249])

**NumPy se mean, median, std calculate karo.**

In [86]:
np.mean(ts)

np.float64(203.312)

In [88]:
np.std(ts)

np.float64(42.75058661585827)

**Random 50 students ka sample banao.**

In [114]:
sample_50 = df.sample(50)

print(sample_50)

     gender race/ethnicity parental level of education         lunch  \
139    male        group D                some college      standard
390    male        group E            some high school  free/reduced
636  female        group B                 high school  free/reduced
314  female        group C           bachelor's degree      standard
711  female        group E            some high school      standard
308  female        group B          associate's degree  free/reduced
140  female        group D            some high school      standard
100    male        group B                some college      standard
47   female        group C                 high school      standard
714  female        group B            some high school      standard
485    male        group C                 high school      standard
167  female        group B             master's degree  free/reduced
103    male        group B                 high school      standard
927  female        group D                 high school  free/reduced
267  female        group D                 high school      standard
414  female        group C           bachelor's degree  free/reduced
791  female        group D                some college  free/reduced
866    male        group C                 high school  free/reduced
900    male        group D             master's degree      standard
58     male        group D                some college      standard
757    male        group E           bachelor's degree  free/reduced
262  female        group C            some high school  free/reduced
183  female        group D          associate's degree      standard
246    male        group E          associate's degree      standard
395    male        group A                 high school  free/reduced
606  female        group C          associate's degree      standard
708    male        group D                 high school      standard
766  female        group C                 high school      standard
119  female        group C                some college      standard
419    male        group E                 high school  free/reduced
848  female        group C                 high school      standard
181  female        group C                some college  free/reduced
736    male        group C          associate's degree      standard
48   female        group D          associate's degree  free/reduced
483    male        group A                 high school      standard
125  female        group B                 high school      standard
237  female        group D            some high school      standard
628    male        group D                some college  free/reduced
31   female        group B                some college      standard
568    male        group B                 high school  free/reduced
134    male        group D           bachelor's degree  free/reduced
967    male        group C                some college      standard
973  female        group D                some college  free/reduced
614  female        group A          associate's degree      standard
284  female        group B            some high school      standard
278  female        group C            some high school  free/reduced
449    male        group B          associate's degree      standard
980  female        group B                 high school  free/reduced
391  female        group D                some college      standard
29   female        group D             master's degree      standard

    test preparation course  math score  reading score  writing score  \
139               completed          71             61             69
390               completed          73             67             59
636               completed          67             80             81
314               completed          59             64             75
711               completed          80             85             85
308                    none          53             71             67
140                    none          76             72             71
100                    none          79             67             67
47                     none          66             71             76
714               completed          60             70             74
485                    none          70             74             71
167               completed          58             76             78
103               completed          60             44             47
927               completed          65             61             71
267                    none          69             72             77
414               completed          51             72             79
791                    none          60             66             70
866                    none          59             53             52
900                    none          85             84             89
58                completed          58             59             58
757               completed          70             68             72
262                    none          44             50             51
183                    none          65             69             70
246                    none          89             76             74
395                    none          48             45             41
606                    none          85             84             82
708                    none          89             87             79
766               completed          58             75             77
119                    none          55             69             65
419               completed          57             56             54
848                    none          59             72             68
181                    none          46             64             66
736                    none          92             79             84
48                completed          57             74             76
483                    none          59             52             46
125                    none          87             95             86
237               completed          64             60             74
628                    none          49             57             46
31                     none          63             65             61
568                    none          63             48             47
134               completed          74             79             75
967                    none          63             63             60
973                    none          49             65             61
614                    none          82             93             93
284                    none          37             46             46
278                    none          65             86             80
449                    none          81             73             72
980                    none           8             24             23
391                    none          77             68             77
29                     none          62             70             75

     Total score  avg score pass/fail
139          201  67.000000      pass
390          199  66.333333      pass
636          228  76.000000      pass
314          198  66.000000      pass
711          250  83.333333      pass
308          191  63.666667      pass
140          219  73.000000      pass
100          213  71.000000      pass
47           213  71.000000      pass
714          204  68.000000      pass
485          215  71.666667      pass
167          212  70.666667      pass
103          151  50.333333      pass
927          197  65.666667      pass
267          218  72.666667      pass
414          202  67.333333      pass
791          196  65.333333      pass
866          164  54.666667      pass
900          258  86.000000      pass
58           175  58.333333      pass
757          210  70.000000      pass
262          145  48.333333      pass
183          204  68.000000      pass
246          239  79.666667      pass
395          134  44.666667      pass
606          251  83.666667      pass
708          255  85.000000      pass
766          210  70.000000      pass
119          189  63.000000      pass
419          167  55.666667      pass
848          199  66.333333      pass
181          176  58.666667      pass
736          255  85.000000      pass
48           207  69.000000      pass
483          157  52.333333      pass
125          268  89.333333      pass
237          198  66.000000      pass
628          152  50.666667      pass
31           189  63.000000      pass
568          158  52.666667      pass
134          228  76.000000      pass
967          186  62.000000      pass
973          175  58.333333      pass
614          268  89.333333      pass
284          129  43.000000      fail
278          231  77.000000      pass
449          226  75.333333      pass
980           55  18.333333      fail
391          222  74.000000      pass
29           207  69.000000      pass

**Students ko grades do:
A = 90+
B = 75+
C = 60+
D = 40+
F < 40**