In [1]:
import pandas as pd

# Creation of DAta Frame

In [2]:
df = pd.DataFrame([1,2,3,4,5],columns=['columan name'])

In [3]:
df

   columan name
0             1
1             2
2             3
3             4
4             5

In [4]:
type(df)

pandas.DataFrame

**Multiple columns**

In [5]:
data ={
    'name':['Arun','Amit','Rishabh','Ayush','Aniiee'],
    'age':[20,21,22,23,24],
    'salary':[1000,2000,3000,4000,5000]
}

In [6]:
df = pd.DataFrame(data)

In [7]:
df

      name  age  salary
0     Arun   20    1000
1     Amit   21    2000
2  Rishabh   22    3000
3    Ayush   23    4000
4   Aniiee   24    5000

In [8]:
df.shape

(5, 3)

In [9]:
df.columns

Index(['name', 'age', 'salary'], dtype='str')

**Change Column Name**

In [10]:
df.rename(columns ={"salary" : "monthly_salary"},inplace=True)

In [11]:
df

      name  age  monthly_salary
0     Arun   20            1000
1     Amit   21            2000
2  Rishabh   22            3000
3    Ayush   23            4000
4   Aniiee   24            5000

**information**

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            5 non-null      str
 1   age             5 non-null      int64
 2   monthly_salary  5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

**Show maths calculation**

In [13]:
df.describe()

             age  monthly_salary
count   5.000000         5.00000
mean   22.000000      3000.00000
std     1.581139      1581.13883
min    20.000000      1000.00000
25%    21.000000      2000.00000
50%    22.000000      3000.00000
75%    23.000000      4000.00000
max    24.000000      5000.00000

# Save and load data from csv

In [14]:
df

      name  age  monthly_salary
0     Arun   20            1000
1     Amit   21            2000
2  Rishabh   22            3000
3    Ayush   23            4000
4   Aniiee   24            5000

**SAve csv**

In [15]:
df.to_csv('text_data.csv',index=False)

**Load CSV**

In [16]:
load_data=pd.read_csv('text_data.csv')
load_data

      name  age  monthly_salary
0     Arun   20            1000
1     Amit   21            2000
2  Rishabh   22            3000
3    Ayush   23            4000
4   Aniiee   24            5000

# SElection and Indexing

In [17]:
df

      name  age  monthly_salary
0     Arun   20            1000
1     Amit   21            2000
2  Rishabh   22            3000
3    Ayush   23            4000
4   Aniiee   24            5000

**Single column Name/Label based**

In [18]:
df[["name"]]

      name
0     Arun
1     Amit
2  Rishabh
3    Ayush
4   Aniiee

**multiple column   Name/Label based**

In [19]:
df[['name','age']]

      name  age
0     Arun   20
1     Amit   21
2  Rishabh   22
3    Ayush   23
4   Aniiee   24

**Single row  Name/Label based**

In [20]:
df.loc[df.name=='Arun']

   name  age  monthly_salary
0  Arun   20            1000

**conditional Row  Name/Label based when multiple name in table**

In [21]:
df.loc[(df.name=='Arun')&(df.monthly_salary>500)]

   name  age  monthly_salary
0  Arun   20            1000

**Single row index based**

In [22]:
df.iloc[0]

name              Arun
age                 20
monthly_salary    1000
Name: 0, dtype: object

**Multiple row index based**

In [23]:
df.iloc[0:3] #[start:stop:step]

      name  age  monthly_salary
0     Arun   20            1000
1     Amit   21            2000
2  Rishabh   22            3000

# Filtter dataframe

In [24]:
df

      name  age  monthly_salary
0     Arun   20            1000
1     Amit   21            2000
2  Rishabh   22            3000
3    Ayush   23            4000
4   Aniiee   24            5000

**one condition based**

In [25]:
df[df['age']>22]

     name  age  monthly_salary
3   Ayush   23            4000
4  Aniiee   24            5000

**one condition based using query**

In [26]:
df.query("age>22")

     name  age  monthly_salary
3   Ayush   23            4000
4  Aniiee   24            5000

**multiple condition based**

In [27]:
df[(df['age']>22)&(df['monthly_salary']>4000)]

     name  age  monthly_salary
4  Aniiee   24            5000

**multiple condition based using query**

In [28]:
df.query("age>22 and monthly_salary>4000")

     name  age  monthly_salary
4  Aniiee   24            5000

**do not change shape or not remove other column**

In [29]:
df.where(df['age']>22)

     name   age  monthly_salary
0     NaN   NaN             NaN
1     NaN   NaN             NaN
2     NaN   NaN             NaN
3   Ayush  23.0          4000.0
4  Aniiee  24.0          5000.0

**do not change shape or not remove other column using other**

In [30]:
df.where(df['age']>22,other='not eligible')

           name           age monthly_salary
0  not eligible  not eligible   not eligible
1  not eligible  not eligible   not eligible
2  not eligible  not eligible   not eligible
3         Ayush            23           4000
4        Aniiee            24           5000

# rows column operations [ add,update,delet]

In [31]:
df

      name  age  monthly_salary
0     Arun   20            1000
1     Amit   21            2000
2  Rishabh   22            3000
3    Ayush   23            4000
4   Aniiee   24            5000

**new column add**

In [32]:
df['team'] =['ceo','da','hr','pr','cto']

In [33]:
df

      name  age  monthly_salary team
0     Arun   20            1000  ceo
1     Amit   21            2000   da
2  Rishabh   22            3000   hr
3    Ayush   23            4000   pr
4   Aniiee   24            5000  cto

**new column with multiplication**

In [34]:
df['nonus']=df['monthly_salary']*0.2

In [35]:
df

      name  age  monthly_salary team   nonus
0     Arun   20            1000  ceo   200.0
1     Amit   21            2000   da   400.0
2  Rishabh   22            3000   hr   600.0
3    Ayush   23            4000   pr   800.0
4   Aniiee   24            5000  cto  1000.0

**new rows add**

In [36]:
df.loc[len(df)]=['ankiibot',30,6000,'caster',20000]

In [37]:
df

       name  age  monthly_salary    team    nonus
0      Arun   20            1000     ceo    200.0
1      Amit   21            2000      da    400.0
2   Rishabh   22            3000      hr    600.0
3     Ayush   23            4000      pr    800.0
4    Aniiee   24            5000     cto   1000.0
5  ankiibot   30            6000  caster  20000.0

**Addd values using index value**

In [38]:
df.loc[2,'age']=10

In [39]:
df

       name  age  monthly_salary    team    nonus
0      Arun   20            1000     ceo    200.0
1      Amit   21            2000      da    400.0
2   Rishabh   10            3000      hr    600.0
3     Ayush   23            4000      pr    800.0
4    Aniiee   24            5000     cto   1000.0
5  ankiibot   30            6000  caster  20000.0

**Addd values using name value**

In [40]:
df

       name  age  monthly_salary    team    nonus
0      Arun   20            1000     ceo    200.0
1      Amit   21            2000      da    400.0
2   Rishabh   10            3000      hr    600.0
3     Ayush   23            4000      pr    800.0
4    Aniiee   24            5000     cto   1000.0
5  ankiibot   30            6000  caster  20000.0

In [41]:
df.loc[df.name=='Arun','monthly_salary'] = 40000

In [42]:
df

       name  age  monthly_salary    team    nonus
0      Arun   20           40000     ceo    200.0
1      Amit   21            2000      da    400.0
2   Rishabh   10            3000      hr    600.0
3     Ayush   23            4000      pr    800.0
4    Aniiee   24            5000     cto   1000.0
5  ankiibot   30            6000  caster  20000.0

**Delet rows using index axis**

In [43]:
df.drop(df[df.name=='ankiibot'].index,inplace=True)

In [44]:
df

      name  age  monthly_salary team   nonus
0     Arun   20           40000  ceo   200.0
1     Amit   21            2000   da   400.0
2  Rishabh   10            3000   hr   600.0
3    Ayush   23            4000   pr   800.0
4   Aniiee   24            5000  cto  1000.0

**Delet culumn using index axis**

In [45]:
df=df.drop('nonus',axis=1)

In [46]:
df

      name  age  monthly_salary team
0     Arun   20           40000  ceo
1     Amit   21            2000   da
2  Rishabh   10            3000   hr
3    Ayush   23            4000   pr
4   Aniiee   24            5000  cto

# Shorting

**Ascending  order**

In [47]:
df.sort_values('age')

      name  age  monthly_salary team
2  Rishabh   10            3000   hr
0     Arun   20           40000  ceo
1     Amit   21            2000   da
3    Ayush   23            4000   pr
4   Aniiee   24            5000  cto

**descending order**

In [48]:
df.sort_values('age',ascending=False)

      name  age  monthly_salary team
4   Aniiee   24            5000  cto
3    Ayush   23            4000   pr
1     Amit   21            2000   da
0     Arun   20           40000  ceo
2  Rishabh   10            3000   hr

# Data cleaning

In [49]:
df

      name  age  monthly_salary team
0     Arun   20           40000  ceo
1     Amit   21            2000   da
2  Rishabh   10            3000   hr
3    Ayush   23            4000   pr
4   Aniiee   24            5000  cto

**cahnge column name**

In [50]:
df.rename(columns= {'team':'team1'})

      name  age  monthly_salary team1
0     Arun   20           40000   ceo
1     Amit   21            2000    da
2  Rishabh   10            3000    hr
3    Ayush   23            4000    pr
4   Aniiee   24            5000   cto

**delet row/column**

In [51]:
df.drop(df[df.name=='Ayush'].index)

      name  age  monthly_salary team
0     Arun   20           40000  ceo
1     Amit   21            2000   da
2  Rishabh   10            3000   hr
4   Aniiee   24            5000  cto

**check dupplicates**

In [52]:
df

      name  age  monthly_salary team
0     Arun   20           40000  ceo
1     Amit   21            2000   da
2  Rishabh   10            3000   hr
3    Ayush   23            4000   pr
4   Aniiee   24            5000  cto

# Aggregation / statistics

**mean**

In [53]:
df

      name  age  monthly_salary team
0     Arun   20           40000  ceo
1     Amit   21            2000   da
2  Rishabh   10            3000   hr
3    Ayush   23            4000   pr
4   Aniiee   24            5000  cto

In [54]:
df['age'].mean()

np.float64(19.6)

**sum**

In [55]:
df['age'].sum()

np.int64(98)

**min**

In [56]:
df['age'].min()

np.int64(10)

**max**

In [57]:
df['age'].max()

np.int64(24)

**count**

In [58]:
df.count()

name              5
age               5
monthly_salary    5
team              5
dtype: int64

**frequency count**

In [59]:
df['age'].value_counts()

age
20    1
21    1
10    1
23    1
24    1
Name: count, dtype: int64

# handling missing v alue

In [60]:
df

      name  age  monthly_salary team
0     Arun   20           40000  ceo
1     Amit   21            2000   da
2  Rishabh   10            3000   hr
3    Ayush   23            4000   pr
4   Aniiee   24            5000  cto

**isnull check null values**

In [61]:
import numpy as np

In [62]:
df.loc[df.name =='Ayush','age']=np.nan

In [63]:
df

      name   age  monthly_salary team
0     Arun  20.0           40000  ceo
1     Amit  21.0            2000   da
2  Rishabh  10.0            3000   hr
3    Ayush   NaN            4000   pr
4   Aniiee  24.0            5000  cto

In [64]:
df.isnull()

    name    age  monthly_salary   team
0  False  False           False  False
1  False  False           False  False
2  False  False           False  False
3  False   True           False  False
4  False  False           False  False

**check how many values null in all column**

In [65]:
df.isnull().sum()

name              0
age               1
monthly_salary    0
team              0
dtype: int64

**fill null values**

In [66]:
df.fillna(0)

      name   age  monthly_salary team
0     Arun  20.0           40000  ceo
1     Amit  21.0            2000   da
2  Rishabh  10.0            3000   hr
3    Ayush   0.0            4000   pr
4   Aniiee  24.0            5000  cto

# date and time

In [67]:
df['Date'] = ['2026-01-01','2026-01-15','2016-03-28','2026-03-03','2026-04-04']

In [68]:
df

      name   age  monthly_salary team        Date
0     Arun  20.0           40000  ceo  2026-01-01
1     Amit  21.0            2000   da  2026-01-15
2  Rishabh  10.0            3000   hr  2016-03-28
3    Ayush   NaN            4000   pr  2026-03-03
4   Aniiee  24.0            5000  cto  2026-04-04

In [69]:
df['Date'].dtype

**Conver to date**

In [70]:
df['Date']=pd.to_datetime(df['Date'])

In [71]:
df

      name   age  monthly_salary team       Date
0     Arun  20.0           40000  ceo 2026-01-01
1     Amit  21.0            2000   da 2026-01-15
2  Rishabh  10.0            3000   hr 2016-03-28
3    Ayush   NaN            4000   pr 2026-03-03
4   Aniiee  24.0            5000  cto 2026-04-04

In [72]:
df1=df

In [73]:
df1

      name   age  monthly_salary team       Date
0     Arun  20.0           40000  ceo 2026-01-01
1     Amit  21.0            2000   da 2026-01-15
2  Rishabh  10.0            3000   hr 2016-03-28
3    Ayush   NaN            4000   pr 2026-03-03
4   Aniiee  24.0            5000  cto 2026-04-04

**date month year fformat cahnge**

In [74]:
df1['date2']= ['01-01-2026','02-1-2026','03-02-2026','03-03-2026','04-04-2026']

In [75]:
df1

      name   age  monthly_salary team       Date       date2
0     Arun  20.0           40000  ceo 2026-01-01  01-01-2026
1     Amit  21.0            2000   da 2026-01-15   02-1-2026
2  Rishabh  10.0            3000   hr 2016-03-28  03-02-2026
3    Ayush   NaN            4000   pr 2026-03-03  03-03-2026
4   Aniiee  24.0            5000  cto 2026-04-04  04-04-2026

In [76]:
df1['date2'].dtype

In [77]:
df1['date2']=pd.to_datetime(df1['date2'],format= '%d-%m-%Y')

In [78]:
df1

      name   age  monthly_salary team       Date      date2
0     Arun  20.0           40000  ceo 2026-01-01 2026-01-01
1     Amit  21.0            2000   da 2026-01-15 2026-01-02
2  Rishabh  10.0            3000   hr 2016-03-28 2026-02-03
3    Ayush   NaN            4000   pr 2026-03-03 2026-03-03
4   Aniiee  24.0            5000  cto 2026-04-04 2026-04-04

In [79]:
df1['date2'].dtype

dtype('<M8[us]')

In [80]:
df=df.drop('date2',axis =1)

In [81]:
df

      name   age  monthly_salary team       Date
0     Arun  20.0           40000  ceo 2026-01-01
1     Amit  21.0            2000   da 2026-01-15
2  Rishabh  10.0            3000   hr 2016-03-28
3    Ayush   NaN            4000   pr 2026-03-03
4   Aniiee  24.0            5000  cto 2026-04-04

**Find/show/print all years**

In [82]:
df['Date'].dt.year

0    2026
1    2026
2    2016
3    2026
4    2026
Name: Date, dtype: int32

**Find/show/print all month**

In [83]:
df['Date'].dt.month

0    1
1    1
2    3
3    3
4    4
Name: Date, dtype: int32

**Find/show/print all day or day name**

In [84]:
df['Date'].dt.day
df['Date'].dt.day_name()

0    Thursday
1    Thursday
2      Monday
3     Tuesday
4    Saturday
Name: Date, dtype: str

**Add month column**

In [85]:
df['month']= df['Date'].dt.month

In [86]:
df

      name   age  monthly_salary team       Date  month
0     Arun  20.0           40000  ceo 2026-01-01      1
1     Amit  21.0            2000   da 2026-01-15      1
2  Rishabh  10.0            3000   hr 2016-03-28      3
3    Ayush   NaN            4000   pr 2026-03-03      3
4   Aniiee  24.0            5000  cto 2026-04-04      4

**condition practice**

In [87]:
df[(df["Date"].dt.month == 3) & (df["monthly_salary"] > 3000)]

    name  age  monthly_salary team       Date  month
3  Ayush  NaN            4000   pr 2026-03-03      3

**condition practoice using query**

In [88]:
df.query("month ==3 and monthly_salary > 3000")

    name  age  monthly_salary team       Date  month
3  Ayush  NaN            4000   pr 2026-03-03      3

**Add extra days**

In [89]:
df['Date']+pd.Timedelta(days=90)

0   2026-04-01
1   2026-04-15
2   2016-06-26
3   2026-06-01
4   2026-07-03
Name: Date, dtype: datetime64[us]

#  Group by

In [90]:
df

      name   age  monthly_salary team       Date  month
0     Arun  20.0           40000  ceo 2026-01-01      1
1     Amit  21.0            2000   da 2026-01-15      1
2  Rishabh  10.0            3000   hr 2016-03-28      3
3    Ayush   NaN            4000   pr 2026-03-03      3
4   Aniiee  24.0            5000  cto 2026-04-04      4

**group data**

In [91]:
df.groupby('month')['monthly_salary'].sum()

month
1    42000
3     7000
4     5000
Name: monthly_salary, dtype: int64

**Multiple aggregation operation perform**

In [92]:
df.groupby('month').agg({'monthly_salary':'mean','name':'count'})

       monthly_salary  name
month
1             21000.0     2
3              3500.0     2
4              5000.0     1

# Merge and joint

In [93]:
df1 = {
    'name':['Arun','ankit'],
     'age' : ['10','30']
}

In [94]:
df2 = {
    'name':['Eren','mikasa'],
     'age2' : ['20','40']
}

In [95]:
df1=pd.DataFrame(df1)

In [96]:
df2=pd.DataFrame(df2)

In [97]:
df1

    name age
0   Arun  10
1  ankit  30

In [98]:
df2

     name age2
0    Eren   20
1  mikasa   40

**Joint tables**

In [99]:
pd.merge(df1,df2)

Empty DataFrame
Columns: [name, age, age2]
Index: []

**combine data verical**

In [100]:
pd.concat([df1,df2])

     name  age age2
0    Arun   10  NaN
1   ankit   30  NaN
0    Eren  NaN   20
1  mikasa  NaN   40

**combine data horizontal**

In [101]:
pd.concat([df1,df2],axis=1)

    name age    name age2
0   Arun  10    Eren   20
1  ankit  30  mikasa   40

**Merge**

In [102]:
pd.merge(df1, df2, how='inner',on='name')

Empty DataFrame
Columns: [name, age, age2]
Index: []

In [103]:
df2

     name age2
0    Eren   20
1  mikasa   40