In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('StudentsPerformance.csv')

In [4]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
df.shape

(1000, 8)

In [6]:
df.size

8000

In [7]:
df.head(1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74

In [8]:
df.tail(1)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
999,female,group D,some college,free/reduced,none,77,86,86

In [9]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [10]:
df[["lunch"]]

            lunch
0        standard
1        standard
2        standard
3    free/reduced
4        standard
..            ...
995      standard
996  free/reduced
997  free/reduced
998      standard
999  free/reduced

[1000 rows x 1 columns]

In [11]:
df.loc[df.gender=='female']

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [12]:
df[(df['math score']>70)]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
984,female,group C,some high school,standard,none,74,75,82
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
995,female,group E,master's degree,standard,completed,88,99,95
999,female,group D,some college,free/reduced,none,77,86,86

In [13]:
df.query("`math score`>70 and gender== 'male' and `reading score`<50")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
520,male,group D,some college,standard,none,71,49,52

In [14]:
df.loc[520,'reading score']=50

In [15]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [16]:
df.loc[[520]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
520,male,group D,some college,standard,none,71,50,52

In [17]:
df['reading score'].sum()

np.int64(69170)

In [18]:
df['math score'].max()

np.int64(100)

In [19]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [20]:
df.fillna(0)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [21]:
df.query("`math score`==0")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10

In [22]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [23]:
df.iloc[[58]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
58,male,group D,some college,standard,completed,58,59,58

In [24]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [25]:
df.iloc[[4]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
4,male,group C,some college,standard,none,76,78,75

In [26]:
df.loc[4,'math score']=80

In [27]:
df.iloc[[4]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
4,male,group C,some college,standard,none,80,78,75

In [28]:
df.loc[4,'math score']=np.nan

In [29]:
df.iloc[[4]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
4,male,group C,some college,standard,none,NaN,78,75

In [30]:
df.fillna(50)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72.0,72,74
1,female,group C,some college,standard,completed,69.0,90,88
2,female,group B,master's degree,standard,none,90.0,95,93
3,male,group A,associate's degree,free/reduced,none,47.0,57,44
4,male,group C,some college,standard,none,50.0,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99,95
996,male,group C,high school,free/reduced,none,62.0,55,55
997,female,group C,high school,free/reduced,completed,59.0,71,65
998,female,group D,some college,standard,completed,68.0,78,77
999,female,group D,some college,free/reduced,none,77.0,86,86

In [31]:
df.loc[58,'math score']=90

In [32]:
df.iloc[[58]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
58,male,group D,some college,standard,completed,90.0,59,58

In [33]:
df['total']=np.nan

In [34]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72,74,NaN
1,female,group C,some college,standard,completed,69.0,90,88,NaN
2,female,group B,master's degree,standard,none,90.0,95,93,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57,44,NaN
4,male,group C,some college,standard,none,NaN,78,75,NaN
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99,95,NaN
996,male,group C,high school,free/reduced,none,62.0,55,55,NaN
997,female,group C,high school,free/reduced,completed,59.0,71,65,NaN
998,female,group D,some college,standard,completed,68.0,78,77,NaN
999,female,group D,some college,free/reduced,none,77.0,86,86,NaN

In [35]:
df.fillna('missing')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72,74,missing
1,female,group C,some college,standard,completed,69.0,90,88,missing
2,female,group B,master's degree,standard,none,90.0,95,93,missing
3,male,group A,associate's degree,free/reduced,none,47.0,57,44,missing
4,male,group C,some college,standard,none,missing,78,75,missing
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99,95,missing
996,male,group C,high school,free/reduced,none,62.0,55,55,missing
997,female,group C,high school,free/reduced,completed,59.0,71,65,missing
998,female,group D,some college,standard,completed,68.0,78,77,missing
999,female,group D,some college,free/reduced,none,77.0,86,86,missing

In [36]:
df.loc[999,'total']=100

In [37]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72,74,NaN
1,female,group C,some college,standard,completed,69.0,90,88,NaN
2,female,group B,master's degree,standard,none,90.0,95,93,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57,44,NaN
4,male,group C,some college,standard,none,NaN,78,75,NaN
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99,95,NaN
996,male,group C,high school,free/reduced,none,62.0,55,55,NaN
997,female,group C,high school,free/reduced,completed,59.0,71,65,NaN
998,female,group D,some college,standard,completed,68.0,78,77,NaN
999,female,group D,some college,free/reduced,none,77.0,86,86,100.0

In [38]:
df.query("total==100")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
999,female,group D,some college,free/reduced,none,77.0,86,86,100.0

In [39]:
df.groupby('gender')['reading score'].sum()

gender
female    37611
male      31559
Name: reading score, dtype: int64

In [40]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72,74,NaN
1,female,group C,some college,standard,completed,69.0,90,88,NaN
2,female,group B,master's degree,standard,none,90.0,95,93,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57,44,NaN
4,male,group C,some college,standard,none,NaN,78,75,NaN
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99,95,NaN
996,male,group C,high school,free/reduced,none,62.0,55,55,NaN
997,female,group C,high school,free/reduced,completed,59.0,71,65,NaN
998,female,group D,some college,standard,completed,68.0,78,77,NaN
999,female,group D,some college,free/reduced,none,77.0,86,86,100.0

In [41]:
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72,74,NaN
1,female,group C,some college,standard,completed,69.0,90,88,NaN
2,female,group B,master's degree,standard,none,90.0,95,93,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57,44,NaN
4,male,group C,some college,standard,none,NaN,78,75,NaN
5,female,group B,associate's degree,standard,none,71.0,83,78,NaN
6,female,group B,some college,standard,completed,88.0,95,92,NaN
7,male,group B,some college,free/reduced,none,40.0,43,39,NaN
8,male,group D,high school,free/reduced,completed,64.0,64,67,NaN
9,female,group B,high school,free/reduced,none,38.0,60,50,NaN

In [42]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
995,female,group E,master's degree,standard,completed,88.0,99,95,NaN
996,male,group C,high school,free/reduced,none,62.0,55,55,NaN
997,female,group C,high school,free/reduced,completed,59.0,71,65,NaN
998,female,group D,some college,standard,completed,68.0,78,77,NaN
999,female,group D,some college,free/reduced,none,77.0,86,86,100.0

In [43]:
df.shape

(1000, 9)

In [44]:
df.loc[[0]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72,74,NaN

In [45]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'total'],
      dtype='str')

In [46]:
type(df)

pandas.DataFrame

In [47]:
df.dtypes

gender                             str
race/ethnicity                     str
parental level of education        str
lunch                              str
test preparation course            str
math score                     float64
reading score                    int64
writing score                    int64
total                          float64
dtype: object

In [48]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72,74,NaN
1,female,group C,some college,standard,completed,69.0,90,88,NaN
2,female,group B,master's degree,standard,none,90.0,95,93,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57,44,NaN
4,male,group C,some college,standard,none,NaN,78,75,NaN
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99,95,NaN
996,male,group C,high school,free/reduced,none,62.0,55,55,NaN
997,female,group C,high school,free/reduced,completed,59.0,71,65,NaN
998,female,group D,some college,standard,completed,68.0,78,77,NaN
999,female,group D,some college,free/reduced,none,77.0,86,86,100.0

In [49]:
 df.drop(df.query('`math score`==59').index)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,72.0,72,74,NaN
1,female,group C,some college,standard,completed,69.0,90,88,NaN
2,female,group B,master's degree,standard,none,90.0,95,93,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57,44,NaN
4,male,group C,some college,standard,none,NaN,78,75,NaN
...,...,...,...,...,...,...,...,...,...
994,male,group A,high school,standard,none,63.0,63,62,NaN
995,female,group E,master's degree,standard,completed,88.0,99,95,NaN
996,male,group C,high school,free/reduced,none,62.0,55,55,NaN
998,female,group D,some college,standard,completed,68.0,78,77,NaN
999,female,group D,some college,free/reduced,none,77.0,86,86,100.0

In [50]:
df.loc[0,'math score']=np.nan

In [51]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total
0,female,group B,bachelor's degree,standard,none,NaN,72,74,NaN
1,female,group C,some college,standard,completed,69.0,90,88,NaN
2,female,group B,master's degree,standard,none,90.0,95,93,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57,44,NaN
4,male,group C,some college,standard,none,NaN,78,75,NaN
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99,95,NaN
996,male,group C,high school,free/reduced,none,62.0,55,55,NaN
997,female,group C,high school,free/reduced,completed,59.0,71,65,NaN
998,female,group D,some college,standard,completed,68.0,78,77,NaN
999,female,group D,some college,free/reduced,none,77.0,86,86,100.0

In [60]:
df.query("`math score`==69 and gender=='female'")[['gender','math score']]

     gender  math score
1    female        69.0
15   female        69.0
23   female        69.0
30   female        69.0
63   female        69.0
194  female        69.0
267  female        69.0
342  female        69.0
584  female        69.0
598  female        69.0
649  female        69.0
672  female        69.0
674  female        69.0
828  female        69.0
888  female        69.0
911  female        69.0

In [64]:
df.groupby('gender')['math score'].sum()

gender
female    32890.0
male      33083.0
Name: math score, dtype: float64